#!/bin/sh

if [ "$1" = "--add" ] && [ -n "$2" ]
then
    # Create a Valid Git Project Name from the Argument Supplied in the Arguments Vector.
    PROJECT=$(echo "$2" | sed 's/\.git$\|$/.git/i')
    # Create a Bare Git Project in the Home Directory with the Given Name.
    cd
    git --bare init $PROJECT
elif [ "$1" = "--list" ]
then
    # Log all Git Projects in the Home Directory.
    cd
    for FILE in *.git
    do
        echo "$FILE"
    done
else
    echo "Please Enter a Supported Option:"
    echo "--add <project.git>"
    echo "--list"
fi
