#!/bin/sh

# Log All Available Commands from the Git Shell Commands Directory.
echo "Available commands:"
cd "$(dirname "$0")"
for FILE in *
do
    echo "$FILE"
done
# Exit is an Available Command in a TTY.
echo "exit"
